---
# Basic yaml configuration

# Unity engine options
unity_engine_settings:
    width: 1024
    height: 1024
    quality_level: 1
    time_scale: 1 # Allows for faster training time, but may introduce unwanted physics behaviour
    target_frame_rate: -1
    capture_frame_rate: 60

# City generation options
env_settings:
    seed: 1337
    block_count_x: 2
    block_count_z: 2
    park_ratio: 0.25

# Action space
action_space_settings:
    continuous_actions: true
    available_actions:
        - move_vertical
        - move_horizontal
        - mouse_y
        - mouse_x
        - jump
        - identify_bug

# Observation space
observation_space_settings:
    # Vector observations
    vector_obs_settings:
        position_type: "normalized"
        include_bug_position: false

    # Camera sensor
    camera_settings:
        grayscale: false
        camera_resolution_width: 1024
        camera_resolution_height: 1024 


    # Lidar sensors
    ray_perception_settings:
        ray_perception_plane: 10
        ray_perception_cone : 10
        ray_perception_slice: 10

    # Semantic map sensor
    semantic_map_settings:
        semantic_map_x: 5
        semantic_map_y: 5
        semantic_map_z: 5

# Bugs
bug_settings:
    gadget: 10
    state: 10
    geometry: 10
    physics: 10
    logic: 10
...


